CC=gcc
flag=-Wall -g -O

arr: arr_arg.c
	${CC}  ${flag}  arr_arg.c  -o arr

sprintf: sprintf.c
	${CC} ${flag}  sprintf.c -o sprintf

digui1:digui1.c
	${CC} ${flag}  digui1.c -o  digui1

fibonaqie: fibonaqie.c
	${CC} ${flag} fibonaqie.c -o fibonaqie

digui2: digui2.c
	${CC} ${flag} digui2.c -o digui2

clean:
	rm -rf *.o  arr sprintf digui1 fibonaqie digui2
