CC=gcc
flag=-Wall -g -O

if: if.c
	${CC} ${flag} if.c -o if

elseif: if_else_if.c
	${CC} ${flag}  if_else_if.c  -o  elseif

while: while.c
	${CC} ${flag}  while.c  -o while

while1: while1.c
	${CC} ${flag}  while1.c  -o while1
switch: switch.c
	${CC} ${flag} switch.c  -o switch

enum: enum.c
	${CC} ${flag}  enum.c  -o enum

for:for.c
	${CC}  ${flag}  for.c  -o for

chengbiao: chengfab.c
	${CC} ${flag} chengfab.c  -o chengfa

abc:abc.c
	${CC} ${flag} abc.c -o abc

chengjidan:chengjidan.c
	${CC} ${flag}  chengjidan.c -o chengjidan

clean:
	rm -rf *.o if elseif while while1 enum chengfa chengfab  switch for  abc  chengjidan
