#ifndef QTMINILIBRARY_GLOBAL_H
#define QTMINILIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTMINILIBRARY_LIBRARY)
#  define QTMINILIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define QTMINILIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMINILIBRARY_GLOBAL_H
