CC=gcc
CFLAG=-Wall -g -O

define:define.c
	${CC} ${CFLAG} define.c -o define

scanf:scanf.c
	${CC} ${CFLAG} scanf.c  -o scanf

string1: string1.c
	${CC} ${CFLAG} string1.c -o string1

clean:
	rm -rf *.o  define scanf string1
